/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as ScanRouteImport } from './routes/scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/admin': typeof AdminRoute
  '/campaigns': typeof CampaignsRoute
  '/creator': typeof CreatorRoute
  '/home': typeof HomeRoute
  '/invoices': typeof InvoicesRoute
  '/merchant': typeof MerchantRoute
  '/scan': typeof ScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/admin': typeof AdminRoute
  '/campaigns': typeof CampaignsRoute
  '/creator': typeof CreatorRoute
  '/home': typeof HomeRoute
  '/invoices': typeof InvoicesRoute
  '/merchant': typeof MerchantRoute
  '/scan': typeof ScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/admin': typeof AdminRoute
  '/campaigns': typeof CampaignsRoute
  '/creator': typeof CreatorRoute
  '/home': typeof HomeRoute
  '/invoices': typeof InvoicesRoute
  '/merchant': typeof MerchantRoute
  '/scan': typeof ScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/admin'
    | '/campaigns'
    | '/creator'
    | '/home'
    | '/invoices'
    | '/merchant'
    | '/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/admin'
    | '/campaigns'
    | '/creator'
    | '/home'
    | '/invoices'
    | '/merchant'
    | '/scan'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/admin'
    | '/campaigns'
    | '/creator'
    | '/home'
    | '/invoices'
    | '/merchant'
    | '/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRoute
  AdminRoute: typeof AdminRoute
  CampaignsRoute: typeof CampaignsRoute
  CreatorRoute: typeof CreatorRoute
  HomeRoute: typeof HomeRoute
  InvoicesRoute: typeof InvoicesRoute
  MerchantRoute: typeof MerchantRoute
  ScanRoute: typeof ScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRoute,
  AdminRoute: AdminRoute,
  CampaignsRoute: CampaignsRoute,
  CreatorRoute: CreatorRoute,
  HomeRoute: HomeRoute,
  InvoicesRoute: InvoicesRoute,
  MerchantRoute: MerchantRoute,
  ScanRoute: ScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
